add workflow to enforce group approvals
taikoxyz/trailblazer-adapters pull request #158
Opened 2024-11-07 11:09 UTC by KorbinianK

This pull request introduces a new GitHub Actions workflow to enforce group-based approvals for pull requests. The workflow ensures that at least one member from each of two defined groups approves the pull request before it can be merged.

New workflow for group-based approvals:

* [`.github/workflows/group-approvals.yml`](diffhunk://#diff-df413fd092c86aa541d74c9b959484740a3530c8e69aa8ce7a81af32be8ec04eR1-R44): Added a new workflow that triggers on pull request events and checks if the required approvals from two specified groups are present. If approvals from both groups are not present, the workflow fails and prevents the pull request from being merged.

2024-11-07 15:01 UTC, myronrotter approved these changes

2024-11-07 15:02 UTC, swarna1101 approved these changes

2024-11-07 17:30 UTC, JBScaled approved these changes

2024-11-08 09:02 UTC, myronrotter requested changes

2024-11-08 09:02 UTC, myronrotter commented on .github/workflows/group-approvals.yml
> +    types: [opened, synchronize, reopened, review_requested]
```suggestion
```

2024-11-08 20:46 UTC, myronrotter approved these changes

2024-11-09 18:26 UTC, nickytaiko commented
good to go

2024-11-10 11:28 UTC, nickytaiko approved these changes

2024-11-10 13:01 UTC, merged