Add Gamma - jpg in pr
taikoxyz/trailblazer-adapters pull request #159
Opened 2024-11-08 16:24 UTC by StrategicReserve

![gammalogo](https://github.com/user-attachments/assets/7c1b5dea-1668-4927-ba48-39de1a0a8cf6)

**Pull Request Template**

---

### Add Gamma to whitelist registry

*Ensure the title follows the conventional commit message format (e.g., feat(whitelist): add staking contract for taiko)*

---

### Description

#### What does this PR do?
Adds gamma's contracts and vaults

---

### Checklist

*Ensure all items are checked before merging.*

- [X] I have followed the conventional commit messages standard.
- [X] Any whitelisted contracts added are verified.

---

### Additional Notes

*Any additional information or context that would be helpful for reviewers.*

---

2024-11-08 20:42 UTC, KorbinianK commented
@StrategicReserve please make sure the json is valid (whitespaces)

2024-11-08 20:42 UTC, myronrotter requested changes

2024-11-08 20:42 UTC, myronrotter commented on whitelist/protocols.json
> +      "0x3ef3d8ba38ebe18db133cec108f4d14ce00dd9ae"
Please remove trailing whitespaces.

2024-11-10 09:28 UTC, myronrotter approved these changes

2024-11-10 11:30 UTC, nickytaiko approved these changes

2024-11-10 11:41 UTC, swarna1101 approved these changes

2024-11-10 13:04 UTC, KorbinianK approved these changes

2024-11-12 01:16 UTC, merged