feat: avalon new contract
taikoxyz/trailblazer-adapters pull request #177
Opened 2024-12-05 06:38 UTC by jasmin-avalon

feat: avalon new contract

2024-12-10 10:24 UTC, myronrotter commented
@jasmin-avalon still draft?

2024-12-13 00:55 UTC, jasmin-avalon commented
Please review. Thanks.

2024-12-13 09:00 UTC, bennettyong approved these changes

2024-12-13 09:06 UTC, myronrotter requested changes

2024-12-13 09:06 UTC, myronrotter commented on whitelist/protocols.json
> +      "0xa57609391A61d10094493e557C4b400b15d4626E"
@jasmin-avalon contract seems not to be verified.

2024-12-13 16:29 UTC, jasmin-avalon commented
@myronrotter Hi. Just made a commit to use a new contract with verification.

2024-12-14 04:43 UTC, swarna1101 approved these changes

2024-12-16 10:50 UTC, myronrotter commented
As discussed @swarna1101, closing this PR.

2024-12-16 10:50 UTC, closed without merging